Feature/readme file completition
scanterra/geonode pull request #5
Opened 2020-10-06 19:25 UTC by marcelorubini

## Tarea de Origen

https://github.com/scanterra/scanterra_quickstart/issues/6

## Descripcion

Agrega conocimiento general al repositorio.

2020-10-09 20:21 UTC, asassano commented
@cristiandley @LaimeJesus lo pueden controlar y aprobar. Gracias

2020-10-09 20:23 UTC, asassano commented
@cristiandley @LaimeJesus lo pueden controlar y aprobar si corresponde. Gracias

2020-10-13 10:34 UTC, cristiandley requested changes

2020-10-13 10:34 UTC, cristiandley commented on README.md
> +Esta versión es una replica de la que actualmente esta funcionando en los servidores de PROD.
Por que es una "replica" ?

2020-10-13 12:27 UTC, LaimeJesus commented on README.md
> +Esta versión es una replica de la que actualmente esta funcionando en los servidores de PROD.
@cristiandley Se refiere a que estamos usando una versión modificada del framework Geonode con los cambios implementados en los servidores.

2020-10-19 10:57 UTC, cristiandley commented on README.md
> +Esta versión es una replica de la que actualmente esta funcionando en los servidores de PROD.
Especifiquen eso. Replica suena a una instancia clonada, no una modificada.

2020-10-19 11:59 UTC, marcelorubini commented on README.md
> +Esta versión es una replica de la que actualmente esta funcionando en los servidores de PROD.
Hecho

2020-10-20 21:36 UTC, asassano commented
@cristiandley esta aclarado?? ya lo aprobaste??

2020-10-23 17:31 UTC, cristiandley approved these changes

2020-12-15 20:10 UTC, LaimeJesus approved these changes

2020-12-23 17:45 UTC, asassano commented
@LaimeJesus se podrás megear este PR??

2020-12-23 17:46 UTC, asassano approved these changes
@marcelorubini @LaimeJesus mergear

2021-04-26 04:02 UTC, merged